### PR TITLE
Update retroarch.cfg video_message_color

### PR DESCRIPTION
**Pull request by RobLoach**
`video_msg_color_*` is now `video_message_color`.

### CODE REVIEW

**Comment by Stevoisiak** [comment]
I intentionally renamed the variables to `video_msg_color_r`. According to `configuration.h`, the names were updated at some point.

https://github.com/libretro/RetroArch/blob/master/configuration.h#L274-L279

**Comment by RobLoach** [comment]
Just pulled `master`, and changed the values to 255,249,0.... When saved, the updated values in retroarch.cfg are...
```
video_message_color = "fff900"
```

Seems the values are bitshifted when loaded/saved from/to hex values.

**Comment by Stevoisiak** [comment]
@RobLoach Can you make this a PR to revert https://github.com/Stevoisiak/RetroArch/commit/5061bc5a65d8d4fac9cdefeaa9aaf8a511389441? If the variable names are changed, it should probably be handled with a separate PR.

**Comment by RobLoach** [comment]
There's other good changes in that commit. Having git history is okay, doesn't hurt anything :wink:

**Comment by Stevoisiak** [comment]
@RobLoach I was more concerned about the other renamed `msg` variables from that commit.

**Comment by RobLoach** [comment]
@Stevoisiak Good find... Updated here. These are all good changes, I like the clean up in retroarch.cfg.

**Comment by RobLoach** [comment]
Thanks! 👍

**Pull request closed without merging**
